stages:
#  get_model_parameters:
#    cmd: python src/get_model_parameters.py --config=params.yaml
#    deps:
#      - src/feature_engineering.py
#      - src/feature_selection.py
#      - src/cross_validation.py
#      - src/model_optimization.py
#    outs:
#    - data/processed/train.csv
#    - data/processed/test.csv
#    - data/processed/label_encoding.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - src/train_and_evaluate.py
    params:
      - estimators.RidgeRegression.params.alpha