base:
  project: germany_house_rent_project
  number_of_features_to_select: 40
  random_state: 42
  test_size: 0.2
  k_value: 4
  target_col: totalRent

data_source:
  sql_source: data_given/house_rent_germany_data.csv

train_test_path:
  train_data: data/processed/train.csv
  test_data: data/processed/test.csv

estimators:
  RidgeRegression:
    params:
      alpha: 0.03

model_dir: saved_models

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Ridge regression
  run_name: mlops
  registered_model_name: RidgeRegressionModel
  remote_server_uri: http://0.0.0.0:1234